name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Install .Net 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Get version
        id: get-version
        shell: pwsh
        run: |
          $version = [System.Version]::Parse("${{ github.ref_name }}".Replace('v', '')).ToString()
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo $version

  publish:
    needs: get-version
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/publish-nuget-packages.yaml@ac0409bf1d88593678bfc87b435283d4ac6708c6
    with:
      version: ${{ needs.get-version.outputs.version }}
      use-nuget: true
      use-github: false
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
